<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    /**
     * Seed the tours table with demo content.
     */
    public function run(): void
    {
        $tours = [
            [
                'title' => 'Discover Japan',
                'slug' => 'discover-japan',
                'overview' => 'Experience the perfect blend of ancient traditions and modern innovation in Japan. This comprehensive tour takes you through bustling Tokyo, historic Kyoto, and vibrant Osaka.',
                'location' => 'Tokyo, Kyoto, Osaka',
                'duration' => '10 Days / 9 Nights',
                'price' => 2499,
                'type' => 'international',
                'highlights' => [
                    'Visit iconic Tokyo Tower and Shibuya Crossing',
                    'Explore ancient temples in Kyoto',
                    'Traditional tea ceremony experience',
                    'Mount Fuji day trip',
                    'Osaka street food tour',
                    'Cherry blossom viewing (seasonal)',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival in Tokyo', 'description' => 'Arrive at Narita Airport, transfer to hotel, evening orientation walk in Shibuya'],
                    ['day' => 2, 'title' => 'Tokyo City Tour', 'description' => 'Visit Senso-ji Temple, Tokyo Tower, Imperial Palace, and Akihabara district'],
                    ['day' => 3, 'title' => 'Mount Fuji Day Trip', 'description' => 'Full day excursion to Mount Fuji and Hakone hot springs'],
                    ['day' => 4, 'title' => 'Tokyo to Kyoto', 'description' => 'Bullet train to Kyoto, check-in, evening stroll in Gion district'],
                    ['day' => 5, 'title' => 'Kyoto Temples', 'description' => 'Visit Kinkaku-ji (Golden Pavilion), Fushimi Inari, and Kiyomizu-dera'],
                    ['day' => 6, 'title' => 'Kyoto Cultural Experience', 'description' => 'Traditional tea ceremony, bamboo forest walk in Arashiyama'],
                    ['day' => 7, 'title' => 'Kyoto to Osaka', 'description' => 'Transfer to Osaka, visit Osaka Castle, Dotonbori district'],
                    ['day' => 8, 'title' => 'Osaka Exploration', 'description' => 'Universal Studios Japan or Nara day trip to see deer and temples'],
                    ['day' => 9, 'title' => 'Osaka Free Day', 'description' => 'Shopping in Shinsaibashi, street food tour, optional activities'],
                    ['day' => 10, 'title' => 'Departure', 'description' => 'Transfer to Kansai Airport for departure flight'],
                ],
                'available_dates' => [
                    '2024-03-15' => 'March 15, 2024',
                    '2024-04-10' => 'April 10, 2024',
                    '2024-05-05' => 'May 5, 2024',
                    '2024-06-20' => 'June 20, 2024',
                ],
                'status' => 'active',
                'is_featured' => true,
                'thumbnail_image' => 'images/tours/japan.jpg',
                'banner_image' => 'images/gallery/japan-1.jpg',
                'gallery_images' => [
                    'images/gallery/japan-1.jpg',
                    'images/gallery/japan-2.jpg',
                    'images/gallery/japan-3.jpg',
                    'images/gallery/japan-4.jpg',
                ],
            ],
            [
                'title' => 'Northern Pakistan',
                'slug' => 'northern-pakistan',
                'overview' => 'Embark on an unforgettable journey through the majestic mountains of Northern Pakistan. Experience breathtaking landscapes, warm hospitality, and adventure of a lifetime.',
                'location' => 'Hunza, Skardu, Fairy Meadows',
                'duration' => '7 Days / 6 Nights',
                'price' => 899,
                'type' => 'domestic',
                'highlights' => [
                    'Visit Hunza Valley and Baltit Fort',
                    'Explore Skardu and Shangrila Resort',
                    'Trek to Fairy Meadows with Nanga Parbat views',
                    'Experience local culture and cuisine',
                    'Visit Attabad Lake',
                    'Professional mountain guides',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Islamabad to Hunza', 'description' => 'Drive via Karakoram Highway, stop at scenic viewpoints, reach Hunza in evening'],
                    ['day' => 2, 'title' => 'Hunza Valley Exploration', 'description' => 'Visit Baltit Fort, Altit Fort, Eagles Nest viewpoint, Karimabad bazaar'],
                    ['day' => 3, 'title' => 'Attabad Lake & Passu', 'description' => 'Boat ride in Attabad Lake, visit Passu Cones, suspension bridge walk'],
                    ['day' => 4, 'title' => 'Hunza to Skardu', 'description' => 'Scenic drive to Skardu via Deosai Plains or the main route (seasonal)'],
                    ['day' => 5, 'title' => 'Skardu Sightseeing', 'description' => 'Visit Shangrila Resort, Kachura Lake, Skardu Fort, local bazaars'],
                    ['day' => 6, 'title' => 'Fairy Meadows Trek', 'description' => 'Drive to Raikot Bridge, jeep ride and trek to Fairy Meadows, Nanga Parbat views'],
                    ['day' => 7, 'title' => 'Return to Islamabad', 'description' => 'Morning at Fairy Meadows, return journey to Islamabad'],
                ],
                'available_dates' => [
                    '2024-06-01' => 'June 1, 2024',
                    '2024-07-15' => 'July 15, 2024',
                    '2024-08-10' => 'August 10, 2024',
                    '2024-09-05' => 'September 5, 2024',
                ],
                'status' => 'active',
                'is_featured' => true,
                'thumbnail_image' => 'images/tours/pakistan.jpg',
                'banner_image' => 'images/gallery/pakistan-1.jpg',
                'gallery_images' => [
                    'images/gallery/pakistan-1.jpg',
                    'images/gallery/pakistan-2.jpg',
                    'images/gallery/pakistan-3.jpg',
                    'images/gallery/pakistan-4.jpg',
                ],
            ],
            [
                'title' => 'European Highlights',
                'slug' => 'european-highlights',
                'overview' => 'Discover the best of Europe in this comprehensive tour covering three iconic cities. Experience world-class art, architecture, cuisine, and culture.',
                'location' => 'Paris, Rome, Barcelona',
                'duration' => '14 Days / 13 Nights',
                'price' => 3299,
                'type' => 'international',
                'highlights' => [
                    'Eiffel Tower and Louvre Museum in Paris',
                    'Colosseum and Vatican City in Rome',
                    'Sagrada Familia and Park Güell in Barcelona',
                    'High-speed train experiences',
                    'Guided city tours with local experts',
                    'Free time for personal exploration',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival in Paris', 'description' => 'Airport pickup, hotel check-in, evening Seine River cruise'],
                    ['day' => 2, 'title' => 'Paris City Tour', 'description' => 'Visit Eiffel Tower, Arc de Triomphe, Champs-Élysées'],
                    ['day' => 3, 'title' => 'Louvre & Versailles', 'description' => 'Morning at Louvre Museum, afternoon Palace of Versailles'],
                    ['day' => 4, 'title' => 'Paris Free Day', 'description' => 'Optional: Disneyland Paris or Montmartre exploration'],
                    ['day' => 5, 'title' => 'Paris to Rome', 'description' => 'High-speed train or flight to Rome, evening Trastevere district'],
                    ['day' => 6, 'title' => 'Ancient Rome', 'description' => 'Colosseum, Roman Forum, Palatine Hill guided tour'],
                    ['day' => 7, 'title' => 'Vatican City', 'description' => 'St. Peters Basilica, Vatican Museums, Sistine Chapel'],
                    ['day' => 8, 'title' => 'Rome Exploration', 'description' => 'Trevi Fountain, Spanish Steps, Pantheon, gelato tasting'],
                    ['day' => 9, 'title' => 'Rome Free Day', 'description' => 'Optional: Pompeii day trip or shopping in Via Condotti'],
                    ['day' => 10, 'title' => 'Rome to Barcelona', 'description' => 'Flight to Barcelona, evening Las Ramblas walk'],
                    ['day' => 11, 'title' => 'Gaudí Architecture', 'description' => 'Sagrada Familia, Park Güell, Casa Batlló'],
                    ['day' => 12, 'title' => 'Barcelona Culture', 'description' => 'Gothic Quarter, La Boqueria Market, Barcelona Cathedral'],
                    ['day' => 13, 'title' => 'Beach & Montjuïc', 'description' => 'Barceloneta Beach, Montjuïc Castle, Magic Fountain show'],
                    ['day' => 14, 'title' => 'Departure', 'description' => 'Last-minute shopping, airport transfer'],
                ],
                'available_dates' => [
                    '2024-05-01' => 'May 1, 2024',
                    '2024-06-15' => 'June 15, 2024',
                    '2024-07-20' => 'July 20, 2024',
                    '2024-08-25' => 'August 25, 2024',
                ],
                'status' => 'active',
                'is_featured' => true,
                'thumbnail_image' => 'images/tours/europe.jpg',
                'banner_image' => 'images/gallery/europe-1.jpg',
                'gallery_images' => [
                    'images/gallery/europe-1.jpg',
                    'images/gallery/europe-2.jpg',
                    'images/gallery/europe-3.jpg',
                    'images/gallery/europe-4.jpg',
                ],
            ],
            [
                'title' => 'Thailand Paradise',
                'slug' => 'thailand-beach-paradise',
                'overview' => 'Sun-kissed beaches, emerald waters, and buzzing city life. From Bangkok\'s temples and markets to Phuket\'s island-hopping and Krabi\'s limestone cliffs, this is Thailand at its best.',
                'location' => 'Phuket, Bangkok, Krabi',
                'duration' => '8 Days / 7 Nights',
                'price' => 1799,
                'type' => 'international',
                'highlights' => [
                    'Grand Palace and Wat Pho in Bangkok',
                    'Floating market experience',
                    'Phuket island-hopping adventure',
                    'Krabi Railay Beach and Ao Nang promenade',
                    'Thai cooking class',
                    'Evening street food tours',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrive Bangkok', 'description' => 'Airport pickup, hotel check-in, evening tuk-tuk ride and street food tasting'],
                    ['day' => 2, 'title' => 'Bangkok Temples & Markets', 'description' => 'Grand Palace, Wat Pho, Long-tail boat on canals, Asiatique night market'],
                    ['day' => 3, 'title' => 'Bangkok to Phuket', 'description' => 'Flight to Phuket, beach time, sunset at Promthep Cape'],
                    ['day' => 4, 'title' => 'Phuket Islands', 'description' => 'Full-day speedboat tour to Phi Phi/Maya Bay or James Bond Island (seasonal)'],
                    ['day' => 5, 'title' => 'Phuket to Krabi', 'description' => 'Scenic transfer to Krabi, relax at Ao Nang, optional Thai massage'],
                    ['day' => 6, 'title' => 'Krabi Adventure', 'description' => 'Railay Beach, Phra Nang Cave, kayaking or snorkeling options'],
                    ['day' => 7, 'title' => 'Krabi Free Day', 'description' => 'Optional cooking class, Emerald Pool & Hot Springs excursion'],
                    ['day' => 8, 'title' => 'Departure', 'description' => 'Transfer to Krabi/Phuket airport for onward flight'],
                ],
                'available_dates' => [
                    '2024-02-10' => 'February 10, 2024',
                    '2024-03-25' => 'March 25, 2024',
                    '2024-04-15' => 'April 15, 2024',
                    '2024-05-30' => 'May 30, 2024',
                ],
                'status' => 'active',
                'is_featured' => true,
                'thumbnail_image' => 'images/tours/thailand.jpg',
                'banner_image' => 'images/gallery/thailand-1.jpg',
                'gallery_images' => [
                    'images/gallery/thailand-1.jpg',
                    'images/gallery/thailand-2.jpg',
                    'images/gallery/thailand-3.jpg',
                    'images/gallery/thailand-4.jpg',
                ],
            ],
            [
                'title' => 'Dubai Extravaganza',
                'slug' => 'dubai-extravaganza',
                'overview' => 'A showcase of futuristic architecture, desert adventures, and luxury shopping. Discover Dubai\'s glittering skyline and the cultural gems of Abu Dhabi.',
                'location' => 'Dubai, Abu Dhabi',
                'duration' => '5 Days / 4 Nights',
                'price' => 1299,
                'type' => 'international',
                'highlights' => [
                    'Burj Khalifa At The Top (non-peak)',
                    'Dubai Marina & Palm Jumeirah photo stops',
                    'Desert safari with dune bashing and BBQ dinner',
                    'Abu Dhabi Sheikh Zayed Grand Mosque',
                    'Old Dubai souks and Dubai Creek',
                    'Dubai Mall fountain show',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrive Dubai', 'description' => 'Airport transfer, check-in, evening Dubai Mall & fountain show'],
                    ['day' => 2, 'title' => 'Modern Dubai', 'description' => 'Marina walk, Palm Jumeirah photo stops, Burj Khalifa entry'],
                    ['day' => 3, 'title' => 'Desert Safari', 'description' => 'Afternoon dune bashing, camel ride, sandboarding, live entertainment, BBQ dinner'],
                    ['day' => 4, 'title' => 'Abu Dhabi Day Trip', 'description' => 'Sheikh Zayed Grand Mosque, Corniche drive, optional Louvre Abu Dhabi'],
                    ['day' => 5, 'title' => 'Old Dubai & Departure', 'description' => 'Gold & Spice Souks, Abra ride on Dubai Creek, airport transfer'],
                ],
                'available_dates' => [
                    '2024-12-01' => 'December 1, 2024',
                    '2024-12-15' => 'December 15, 2024',
                    '2025-01-10' => 'January 10, 2025',
                    '2025-02-05' => 'February 5, 2025',
                ],
                'status' => 'active',
                'is_featured' => false,
                'thumbnail_image' => 'images/tours/dubai.jpg',
                'banner_image' => 'images/gallery/dubai-1.jpg',
                'gallery_images' => [
                    'images/gallery/dubai-1.jpg',
                    'images/gallery/dubai-2.jpg',
                    'images/gallery/dubai-3.jpg',
                    'images/gallery/dubai-4.jpg',
                ],
            ],
            [
                'title' => 'Lahore Heritage Tour',
                'slug' => 'lahore-heritage-tour',
                'overview' => 'Dive into the cultural capital of Pakistan. Mughal-era monuments, rich cuisine, and vibrant bazaars make Lahore unforgettable.',
                'location' => 'Lahore',
                'duration' => '3 Days / 2 Nights',
                'price' => 399,
                'type' => 'domestic',
                'highlights' => [
                    'Badshahi Mosque and Lahore Fort (Shahi Qila)',
                    'Walled City heritage walk and Food Street',
                    'Shalimar Gardens and Lahore Museum',
                    'Wagah Border flag-lowering ceremony',
                    'Anarkali & Liberty market shopping',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival & Old Lahore', 'description' => 'Check-in, visit Badshahi Mosque, Lahore Fort, Shahi Hammam, evening at Food Street'],
                    ['day' => 2, 'title' => 'Gardens & Museums', 'description' => 'Shalimar Gardens, Lahore Museum, Anarkali Bazaar, evening Wagah Border ceremony'],
                    ['day' => 3, 'title' => 'Modern Lahore & Departure', 'description' => 'Liberty Market, MM Alam Road cafés, souvenir shopping, depart for home'],
                ],
                'available_dates' => [
                    '2024-03-01' => 'March 1, 2024',
                    '2024-03-20' => 'March 20, 2024',
                    '2024-04-10' => 'April 10, 2024',
                    '2024-05-01' => 'May 1, 2024',
                ],
                'status' => 'active',
                'is_featured' => false,
                'thumbnail_image' => 'images/tours/lahore.jpg',
                'banner_image' => 'images/gallery/lahore-1.jpg',
                'gallery_images' => [
                    'images/gallery/lahore-1.jpg',
                    'images/gallery/lahore-2.jpg',
                    'images/gallery/lahore-3.jpg',
                    'images/gallery/lahore-4.jpg',
                ],
            ],
            [
                'title' => 'Coastal Pakistan Escape',
                'slug' => 'coastal-pakistan-escape',
                'overview' => 'Follow the Makran Coastal Highway to pristine beaches, dramatic cliffs, and starry skies. A laid-back journey across Pakistan\'s south coast.',
                'location' => 'Karachi, Gwadar, Ormara',
                'duration' => '5 Days / 4 Nights',
                'price' => 599,
                'type' => 'domestic',
                'highlights' => [
                    'Sunset at Ormara Hammerhead',
                    'Kund Malir Beach & Princess of Hope',
                    'Gwadar port city viewpoints',
                    'Hingol National Park landscapes',
                    'Karachi heritage & food tour',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Karachi Arrival & City Flavor', 'description' => 'Check-in, Clifton & Seaview drive, Burns Road food trail'],
                    ['day' => 2, 'title' => 'Karachi to Ormara', 'description' => 'Drive via Makran Coastal Highway, Kund Malir & Princess of Hope, sunset at Ormara'],
                    ['day' => 3, 'title' => 'Ormara to Gwadar', 'description' => 'Hammerhead viewpoint, Hingol National Park photo stops, arrive Gwadar'],
                    ['day' => 4, 'title' => 'Explore Gwadar', 'description' => 'Gwadar Port viewpoint, Koh-e-Batil, beaches, seafood dinner'],
                    ['day' => 5, 'title' => 'Return to Karachi', 'description' => 'Coastal drive back with scenic stops, drop-off in Karachi'],
                ],
                'available_dates' => [
                    '2024-11-01' => 'November 1, 2024',
                    '2024-11-20' => 'November 20, 2024',
                    '2024-12-10' => 'December 10, 2024',
                    '2025-01-05' => 'January 5, 2025',
                ],
                'status' => 'active',
                'is_featured' => false,
                'thumbnail_image' => 'images/tours/coast.jpg',
                'banner_image' => 'images/gallery/coast-1.jpg',
                'gallery_images' => [
                    'images/gallery/coast-1.jpg',
                    'images/gallery/coast-2.jpg',
                    'images/gallery/coast-3.jpg',
                    'images/gallery/coast-4.jpg',
                ],
            ],
            [
                'title' => 'Swat Valley Discovery',
                'slug' => 'swat-valley-discovery',
                'overview' => 'Lush valleys, rivers, and alpine lakes. Discover Swat\'s beauty from Mingora to Kalam, with an unforgettable trip to Mahodand Lake (seasonal access).',
                'location' => 'Swat, Kalam, Mahodand',
                'duration' => '4 Days / 3 Nights',
                'price' => 499,
                'type' => 'domestic',
                'highlights' => [
                    'Malam Jabba chairlift (seasonal)',
                    'Kalam Bazaar and Ushu Forest',
                    'Mahodand Lake jeep excursion',
                    'Swat Museum & Mingora riverfront',
                    'Local trout dinner experience',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Islamabad to Swat', 'description' => 'Drive to Swat, check-in, river walk and local dinner'],
                    ['day' => 2, 'title' => 'Malam Jabba & Mingora', 'description' => 'Malam Jabba chairlift/zipline (seasonal), Swat Museum, evening café by the river'],
                    ['day' => 3, 'title' => 'Kalam & Ushu Forest', 'description' => 'Transfer to Kalam, explore Ushu Forest, trout lunch, bazaar stroll'],
                    ['day' => 4, 'title' => 'Mahodand Lake & Return', 'description' => 'Jeep to Mahodand Lake (weather permitting), drive back towards Islamabad'],
                ],
                'available_dates' => [
                    '2024-07-01' => 'July 1, 2024',
                    '2024-07-20' => 'July 20, 2024',
                    '2024-08-10' => 'August 10, 2024',
                    '2024-08-30' => 'August 30, 2024',
                ],
                'status' => 'active',
                'is_featured' => false,
                'thumbnail_image' => 'images/tours/swat.jpg',
                'banner_image' => 'images/gallery/swat-1.jpg',
                'gallery_images' => [
                    'images/gallery/swat-1.jpg',
                    'images/gallery/swat-2.jpg',
                    'images/gallery/swat-3.jpg',
                    'images/gallery/swat-4.jpg',
                ],
            ],
        ];

        foreach ($tours as $tour) {
            Tour::updateOrCreate(
                ['slug' => $tour['slug']],
                $tour
            );
        }
    }
}
